### ISSUE TITLE
PPI fails to install on a fresh Perl 5.22 system because of missing dependency on File::Remove

### ISSUE THREAD

**Issue by daoswald** [adamkennedy/PPI#170]
PPI fails to install on a reasonably fresh Perl 5.22 system.  It is missing the File::Remove dependency, which apparently isn't named in its prereqs.  This breaks such downstream modules as Test::Perl::Critic

**Comment by wchristian** [comment]
Thanks for the note. I don't have the time at the moment, but i will deal with this late next week.

**Comment by wchristian** [comment]
This has been fixed and released. :)
