### ISSUE TITLE
PPI 1.264 Causes Test Failure in Perl 5.20 & Older

### ISSUE THREAD

**Issue by wbraswell** [adamkennedy/PPI#237]
The latest release of PPI 1.252 (and presumably newer releases) are causing installation errors for Perl::Critic on Perl 5.22 and older:

https://travis-ci.org/Perl-Critic/Perl-Critic/builds/525222639

```
...
Building and testing Perl-Critic-1.132 ... FAIL
! Installing Perl::Critic failed. See /home/travis/.cpanm/work/1556335093.7671/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Perl::Critic' is not installed
! Bailing out the installation for Perl-Critic-More-1.003.
--> Working on Test::Perl::Critic
Fetching http://www.cpan.org/authors/id/P/PE/PETDANCE/Test-Perl-Critic-1.04.tar.gz ... OK
Configuring Test-Perl-Critic-1.04 ... OK
==> Found dependencies: MCE, Perl::Critic, Perl::Critic::Utils, Perl::Critic::Violation
--> Working on MCE
Fetching http://www.cpan.org/authors/id/M/MA/MARIOROY/MCE-1.838.tar.gz ... OK
Configuring MCE-1.838 ... OK
Building and testing MCE-1.838 ... OK
Successfully installed MCE-1.838
! Installing the dependencies failed: Module 'Perl::Critic::Violation' is not installed, Module 'Perl::Critic::Utils' is not installed, Module 'Perl::Critic' is not installed
! Bailing out the installation for Test-Perl-Critic-1.04.
...
```

**Comment by wbraswell** [comment]
@wchristian 
This is related to https://github.com/adamkennedy/PPI/issues/236
They are both causing errors with Perl::Critic which did not exist before.
The difference is this issue is for Perl 5.22 & older, while the other issue is for Perl 5.24 & newer.
Please provide your guidance.

**Comment by wchristian** [comment]
According to the Travis link it appears to be failing on all perl versions?

**Comment by wbraswell** [comment]
@wchristian 
You can see it is failing differently on Perl 5.24 and newer because they have an "X" meaning "failure during build/test", whereas Perl 5.22 and newer has an "!" meaning "failure during install".  That's why I made 2 different issues, this one and https://github.com/adamkennedy/PPI/issues/236.

**Comment by wchristian** [comment]
As discussed on IRC, i rereleased PPI without the Test::InDistDir dependency. Did that improve the situation?

**Comment by wbraswell** [comment]
@wchristian 
We have now upgraded Perl::Critic dev branch to require PPI 1.264, and now we are down to only 1 error for Perl 5.20 and older.
(Thus, I have renamed this issue.)
https://travis-ci.org/Perl-Critic/Perl-Critic/builds/526963275
https://api.travis-ci.org/v3/job/526963280/log.txt
```
t/04_options_processor.t ...................... ok
t/05_utils.t .................................. Having more than one /x regexp modifier is deprecated at /home/travis/.cpanm/work/1556733082.6620/Perl-Critic-1.132/blib/lib/Perl/Critic/Policy/ValuesAndExpressions/RequireInterpolationOfMetachars.pm line 110.
t/05_utils.t .................................. 1/156 
#   Failed test 'parse_arg_list: foo( { bar() }, {}, 'blah' )'
#   at t/05_utils.t line 433.
#     Structures begin differing at:
#          $got->[0] = ARRAY(0x51b5620)
#     $expected->[0] = ' { bar() }'
# Looks like you failed 1 test of 156.
t/05_utils.t .................................. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/156 subtests 
```

**Comment by wchristian** [comment]
Taking a bit of a look at this stuff again. Were the causes for these resolved satisfactorily?

**Comment by wbraswell** [comment]
@wchristian 
Yes Perl::Critic is passing tests now, seems to be good!
https://travis-ci.org/Perl-Critic/Perl-Critic/jobs/617791612
