### ISSUE TITLE
t/21_exhaustive.t: still random failures (PPI-1.264, 1.265)

### ISSUE THREAD

**Issue by eserte** [adamkennedy/PPI#242]
https://github.com/adamkennedy/PPI/issues/239 is not yet completely resolved --- fails are rare now, but still happen.

**Comment by wchristian** [comment]
I reopened the other one. Also, fwiw, i might respond a bit late, but i get emails for every comment and always see them at some point. :)

Please whenever you see a new string trigger that test, please post it. Since it generates random ones it might be new ones.

**Comment by wchristian** [comment]
Ah, and yeah, i saw you add the version up there, that's expected. The last release was a tiny golf.
