### ISSUE TITLE
Remove dependency on File::Remove and migrate tests to File::Temp (or potentially File::Temp::Tiny)

### ISSUE THREAD

**Issue by karenetheridge** [adamkennedy/PPI#83]
Is File::Remove really needed? it's used in a few tests, but it seems that File::Temp would do just as good a job here (plus it's in core).  File::Remove never installs cleanly for me on fresh perls, so it's a big drag when I can't install my entire toolchain in one run. :)

**Comment by wchristian** [comment]
This was resolved by #217
