### ISSUE TITLE
PPI recognize postfix dereference tokens incorrectly

### ISSUE THREAD

**Issue by zdm** [adamkennedy/PPI#88]
tested with:

```
$sref->$*;
$aref->@*;
$aref->$#*;
$href->%*;
$cref->&*;
$gref->**;
```

**Comment by trwyant** [comment]
I am interested in attempting this. My proposed parse is to make them a PPI::Token::Cast. If it's a slice, this would be followed by a PPI::Structure::Subscript. The cast object would contain just the postfix dereference (that is, '$*' and friends), not the right arrow operator.

Comments? Would you prefer another implementation?

**Comment by trwyant** [comment]
Looks like this is already in the Git repository. Thank you very much.

**Comment by zdm** [comment]
Whether this issue fixed? 
It is still present for me.

**Comment by akiym** [comment]
Fixed in version 1.237_001. But it's still dev release.
@wchristian Could you release version 1.238 on CPAN?

**Comment by zdm** [comment]
Current PPI version is 1.270, bug is still exists.

**Comment by wchristian** [comment]
@zdm These tests pass in all tests i've seen of PPI: https://metacpan.org/source/MITHALDU/PPI-1.270/t/ppi_token_unknown.t#L466-600

Can you please give me code that demonstrates the exact bug you're seeing?

**Comment by zdm** [comment]
It is not works for me.
I am using examples from the first message in this issue and get errors.
```
References::ProhibitDoubleSigils - Double-sigil dereference
```
When I disable rule "References::ProhibitDoubleSigils" no errors occurred.

**Comment by wchristian** [comment]
@zdm That's not a bug in PPI, that's a bug in that policy which wasn't updated to take into account that Token::Cast can now NOT have a block after it, if it is preceeded by a dereference operator.

Please report this bug in Perl-Critic. :)
